// vue-version/components/Cart.vue
<script setup lang="ts">
import { computed } from 'vue';
import { X, Trash2, Plus, Minus, ShoppingBag, ArrowRight } from 'lucide-vue-next';
import { CartItem } from '../types';

const props = defineProps<{
  isOpen: boolean;
  cartItems: CartItem[];
}>();

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'update-quantity', productId: string, delta: number): void;
  (e: 'remove-item', productId: string): void;
  (e: 'checkout'): void;
}>();

// CALCULS AVEC DES COMPUTED (Équivalents à useMemo() de React)
const subtotal = computed(() => {
  return props.cartItems.reduce((acc, item) => acc + item.product.price * item.quantity, 0);
});

const isFreeShipping = computed(() => {
  return subtotal.value >= 60;
});

const shippingCost = computed(() => {
  if (subtotal.value === 0) return 0;
  return isFreeShipping.value ? 0 : 4.90;
});

const total = computed(() => {
  return subtotal.value + shippingCost.value;
});

const totalItemsCount = computed(() => {
  return props.cartItems.reduce((acc, item) => acc + item.quantity, 0);
});
</script>

<template>
  <transition name="fade">
    <div 
      v-if="isOpen" 
      class="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex justify-end"
      @click="emit('close')"
    >
      <!-- Panneau coulissant blanc (Arrêt de propagation du clic pour ne pas fermer à l'intérieur) -->
      <transition name="slide">
        <div 
          v-if="isOpen"
          class="w-full max-w-md bg-white h-full shadow-2xl flex flex-col relative"
          @click.stop
        >
          <!-- En-tête du tiroir -->
          <div class="px-6 py-5 border-b border-slate-100 flex items-center justify-between">
            <div class="flex items-center gap-2">
              <ShoppingBag class="w-5 h-5 text-indigo-600" />
              <h2 class="font-sans font-bold text-lg text-slate-800">Votre panier</h2>
              <span class="bg-indigo-50 text-indigo-600 text-xs font-semibold px-2 py-0.5 rounded-full">
                {{ totalItemsCount }}
              </span>
            </div>
            <button
              @click="emit('close')"
              class="p-2 rounded-lg hover:bg-slate-50 text-slate-400 hover:text-slate-600 transition-colors"
            >
              <X class="w-5 h-5" />
            </button>
          </div>

          <!-- LISTE DES ARTICLES DANS LE PANIER -->
          <div class="flex-1 overflow-y-auto p-6 space-y-4">
            <!-- État vide -->
            <div 
              v-if="cartItems.length === 0" 
              class="h-full flex flex-col items-center justify-center text-center space-y-4"
            >
              <div class="w-16 h-16 rounded-full bg-slate-50 flex items-center justify-center text-slate-400">
                <ShoppingBag class="w-8 h-8" />
              </div>
              <div>
                <h3 class="font-sans font-bold text-slate-700 text-base">Votre panier est vide</h3>
                <p class="text-xs text-slate-400 mt-1">Laissez-vous tenter par l'un de nos articles éco-responsables !</p>
              </div>
              <button
                @click="emit('close')"
                class="px-5 py-2 rounded-xl text-xs bg-indigo-50 hover:bg-indigo-100/80 text-indigo-600 font-sans font-semibold transition-colors"
              >
                Continuer mes achats
              </button>
            </div>

            <!-- Liste effective des produits -->
            <div 
              v-else 
              v-for="item in cartItems" 
              :key="item.product.id"
              class="flex gap-4 p-3 rounded-xl border border-slate-100 hover:border-slate-200 transition-colors"
            >
              <!-- Image miniature -->
              <div class="w-20 h-20 bg-slate-50 rounded-lg overflow-hidden shrink-0 border border-slate-100">
                <img
                  :src="item.product.mainImage"
                  :alt="item.product.name"
                  referrerpolicy="no-referrer"
                  class="w-full h-full object-cover"
                />
              </div>

              <!-- Titre, quantité & contrôles -->
              <div class="flex-1 flex flex-col justify-between">
                <div>
                  <div class="flex justify-between items-start gap-2">
                    <h4 class="font-sans font-semibold text-slate-800 text-xs sm:text-sm line-clamp-1">
                      {{ item.product.name }}
                    </h4>
                    <button
                      @click="emit('remove-item', item.product.id)"
                      class="text-slate-400 hover:text-rose-500 transition-colors shrink-0"
                      title="Supprimer l'article"
                    >
                      <Trash2 class="w-4 h-4" />
                    </button>
                  </div>
                  <span class="text-xs text-slate-500 font-sans block mt-0.5 uppercase tracking-wide">
                    {{ item.product.category }}
                  </span>
                </div>

                <div class="flex justify-between items-center mt-2">
                  <!-- Gestion du nombre d'articles +/- -->
                  <div class="flex items-center border border-slate-100 rounded-lg bg-slate-50 p-1">
                    <button
                      @click="emit('update-quantity', item.product.id, -1)"
                      class="p-1 rounded-md text-slate-500 hover:bg-white hover:text-indigo-600 hover:shadow-2xs active:scale-95 shrink-0"
                    >
                      <Minus class="w-3.5 h-3.5" />
                    </button>
                    <span class="w-8 text-center font-mono font-bold text-xs text-slate-700">
                      {{ item.quantity }}
                    </span>
                    <button
                      :disabled="item.quantity >= item.product.stock"
                      @click="emit('update-quantity', item.product.id, 1)"
                      class="p-1 rounded-md text-slate-500 hover:bg-white hover:text-indigo-600 hover:shadow-2xs active:scale-95 disabled:opacity-30 disabled:hover:bg-transparent shrink-0"
                    >
                      <Plus class="w-3.5 h-3.5" />
                    </button>
                  </div>

                  <!-- Prix calculé unitaire/total -->
                  <span class="font-mono font-bold text-xs sm:text-sm text-slate-800">
                    {{ (item.product.price * item.quantity).toFixed(2) }} €
                  </span>
                </div>
              </div>
            </div>
          </div>

          <!-- SECTION DES COMPTES FINAUX (PIED DU TIROIR) -->
          <div v-if="cartItems.length > 0" class="border-t border-slate-100 bg-slate-50/50 p-6 space-y-4">
            
            <!-- Détail financier -->
            <div class="space-y-2 text-sm text-slate-600">
              <div class="flex justify-between font-sans">
                <span>Sous-total</span>
                <span class="font-mono font-semibold">{{ subtotal.toFixed(2) }} €</span>
              </div>
              <div class="flex justify-between font-sans">
                <span>Frais de port</span>
                <span class="font-mono font-semibold" v-if="shippingCost === 0">Offerts</span>
                <span class="font-mono font-semibold" v-else>{{ shippingCost.toFixed(2) }} €</span>
              </div>

              <!-- Jauge de frais de port offert interactive -->
              <div class="pt-2">
                <div v-if="!isFreeShipping" class="space-y-1.5 text-xs text-slate-500">
                  <p>
                    Plus que <strong class="font-mono font-bold text-indigo-500">{{ (60 - subtotal).toFixed(2) }} €</strong> pour profiter de la <strong>livraison gratuite</strong> !
                  </p>
                  <div class="w-full h-1.5 bg-slate-200 rounded-full overflow-hidden">
                    <div 
                      class="h-full bg-indigo-500 transition-all duration-300"
                      :style="{ width: (subtotal / 60 * 100) + '%' }"
                    ></div>
                  </div>
                </div>
                <div v-else class="text-xs text-emerald-600 font-sans font-semibold flex items-center gap-1.5">
                  ✓ Vous bénéficiez de la livraison gratuite !
                </div>
              </div>
            </div>

            <div class="border-t border-slate-200/50 pt-4 flex justify-between items-center text-slate-800">
              <span class="font-sans font-bold text-base">Total TTC</span>
              <span class="font-mono font-black text-lg md:text-xl text-indigo-700">
                {{ total.toFixed(2) }} €
              </span>
            </div>

            <!-- Bouton de validation de commande -->
            <button
              @click="emit('checkout')"
              class="w-full py-4 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-center font-sans font-bold text-sm flex items-center justify-center gap-2 shadow-md shadow-indigo-100 transition-all active:scale-98 cursor-pointer"
            >
              <span>Passer à la caisse</span>
              <ArrowRight class="w-4 h-4 animate-pulse" />
            </button>
          </div>
        </div>
      </transition>
    </div>
  </transition>
</template>

<style scoped>
/* Animations Vue pour le Drawer */
.fade-enter-active, .fade-leave-active {
  transition: opacity 0.3s ease;
}
.fade-enter-from, .fade-leave-to {
  opacity: 0;
}

.slide-enter-active, .slide-leave-active {
  transition: transform 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}
.slide-enter-from, .slide-leave-to {
  transform: translateX(100%);
}
</style>

// src/components/Cart.tsx
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { CartItem } from '../types';
import { X, Plus, Minus, Trash2, ShoppingBag, ArrowRight, ShieldCheck } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

// Props pour le composant Panier.
// Analogie VueJS : Propriétés reçues et événements émis via $emit ou callbacks.
interface CartProps {
  isOpen: boolean;
  onClose: () => void;
  cartItems: CartItem[];
  onUpdateQuantity: (productId: string, delta: number) => void;
  onRemoveItem: (productId: string) => void;
  onCheckout: () => void;
}

export function Cart({
  isOpen,
  onClose,
  cartItems,
  onUpdateQuantity,
  onRemoveItem,
  onCheckout,
}: CartProps) {
  
  // En React, les valeurs calculées se font simplement lors du rendu ou par useMemo.
  // Analogie VueJS : const subtotal = computed(() => ...)
  const subtotal = cartItems.reduce((acc, item) => acc + item.product.price * item.quantity, 0);
  const freeShippingThreshold = 50.00;
  const isFreeShipping = subtotal >= freeShippingThreshold;
  const shippingCost = subtotal === 0 ? 0 : (isFreeShipping ? 0 : 4.90);
  const total = subtotal + shippingCost;
  const totalItemCount = cartItems.reduce((acc, item) => acc + item.quantity, 0);

  return (
    // AnimatePresence permet d'animer les entrées et sorties de composants enfants en React.
    // Analogie VueJS : <transition name="slide"> ... </transition>.
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Arrière-plan flouté d'overlay */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs z-50 transition-opacity"
          />

          {/* Panneau Latéral Coulissant (Cart Drawer) */}
          <motion.div
            initial={{ x: '100%' }}
            animate={{ x: 0 }}
            exit={{ x: '100%' }}
            transition={{ type: 'tween', duration: 0.3 }}
            className="fixed inset-y-0 right-0 max-w-md w-full bg-white shadow-2xl z-50 flex flex-col"
          >
            {/* Header du panier */}
            <div className="p-6 border-b border-slate-100 flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <ShoppingBag className="w-5 h-5 text-indigo-600" />
                <h2 className="font-sans font-bold text-lg text-slate-950">Votre Panier ({totalItemCount})</h2>
              </div>
              <button
                id="cart-close-btn"
                onClick={onClose}
                className="p-1.5 rounded-lg border border-slate-100 hover:border-slate-200 text-slate-500 hover:text-slate-800 transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Liste des Produits ou écran vide */}
            <div className="flex-1 overflow-y-auto px-6 py-4 space-y-4">
              {cartItems.length === 0 ? (
                <div className="h-full flex flex-col items-center justify-center text-center p-8 space-y-4">
                  <div className="w-16 h-16 rounded-full bg-slate-50 flex items-center justify-center text-slate-400">
                    <ShoppingBag className="w-8 h-8" />
                  </div>
                  <div>
                    <h3 className="font-sans font-semibold text-slate-800">Votre panier est vide</h3>
                    <p className="text-xs text-slate-500 mt-1 max-w-xs mx-auto">
                      Explorez notre catalogue et ajoutez des merveilles à votre sélection !
                    </p>
                  </div>
                  <button
                    id="cart-empty-back-btn"
                    onClick={onClose}
                    className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold transition-all"
                  >
                    Découvrir les produits
                  </button>
                </div>
              ) : (
                cartItems.map((item) => {
                  const itemSubtotal = item.product.price * item.quantity;
                  const isMaxReached = item.quantity >= item.product.stock;

                  return (
                    <motion.div
                      key={`cart-item-${item.product.id}`}
                      layout
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="flex gap-4 p-3.5 bg-slate-50/70 border border-slate-100 rounded-xl"
                    >
                      {/* Miniature Image */}
                      <div className="w-16 h-16 rounded-lg bg-white overflow-hidden border border-slate-200 shrink-0">
                        <img
                          src={item.product.mainImage}
                          alt={item.product.name}
                          referrerPolicy="no-referrer"
                          className="w-full h-full object-cover"
                        />
                      </div>

                      {/* Infos produit */}
                      <div className="flex-1 flex flex-col justify-between min-w-0">
                        <div>
                          <div className="flex items-start justify-between gap-1">
                            <h4 className="font-sans font-semibold text-xs text-slate-800 truncate" title={item.product.name}>
                              {item.product.name}
                            </h4>
                            
                            <button
                              id={`cart-remove-${item.product.id}`}
                              onClick={() => onRemoveItem(item.product.id)}
                              className="text-slate-400 hover:text-rose-600 p-1 rounded-sm hover:bg-white transition-colors"
                              title="Retirer cet article"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                          
                          <span className="text-xs font-medium text-slate-500 block">
                            {item.product.price.toLocaleString('fr-FR', { style: 'currency', currency: 'EUR' })}
                          </span>
                        </div>

                        {/* Sélecteur de Quantité */}
                        <div className="flex items-center justify-between mt-2">
                          <div className="flex items-center border border-slate-200 bg-white rounded-lg overflow-hidden">
                            <button
                              id={`cart-qty-desc-${item.product.id}`}
                              onClick={() => onUpdateQuantity(item.product.id, -1)}
                              disabled={item.quantity <= 1}
                              className="p-1 px-1.5 hover:bg-slate-50 text-slate-500 disabled:text-slate-200 disabled:hover:bg-transparent"
                            >
                              <Minus className="w-3 h-3" />
                            </button>
                            
                            <span className="px-3 text-xs font-bold text-slate-700 min-w-6 text-center select-none">
                              {item.quantity}
                            </span>
                            
                            <button
                              id={`cart-qty-inc-${item.product.id}`}
                              onClick={() => onUpdateQuantity(item.product.id, 1)}
                              disabled={isMaxReached}
                              className="p-1 px-1.5 hover:bg-slate-50 text-slate-500 disabled:text-slate-200 disabled:hover:bg-transparent"
                              title={isMaxReached ? "Limite de stock atteinte" : "Augmenter la quantité"}
                            >
                              <Plus className="w-3 h-3" />
                            </button>
                          </div>

                          {/* Sous-total item */}
                          <span className="font-sans font-bold text-xs text-slate-800">
                            {itemSubtotal.toLocaleString('fr-FR', { style: 'currency', currency: 'EUR' })}
                          </span>
                        </div>
                        
                        {/* Alerte stock limite */}
                        {isMaxReached && (
                          <span className="text-[10px] text-amber-600 font-semibold mt-1 block">
                            Maximum disponible en stock
                          </span>
                        )}
                      </div>
                    </motion.div>
                  );
                })
              )}
            </div>

            {/* Footer : Totaux & Checkout */}
            {cartItems.length > 0 && (
              <div className="p-6 border-t border-slate-100 bg-slate-50 space-y-4">
                
                {/* Tableau récapitulatif */}
                <div className="space-y-2 text-sm text-slate-600">
                  <div className="flex justify-between">
                    <span>Sous-total articles</span>
                    <span className="font-semibold text-slate-800">
                      {subtotal.toLocaleString('fr-FR', { style: 'currency', currency: 'EUR' })}
                    </span>
                  </div>

                  <div className="flex justify-between items-center text-xs">
                    <span>
                      Livraison Standard {isFreeShipping && <span className="bg-emerald-100 text-emerald-800 font-bold px-1.5 py-0.2 rounded-sm ml-1.5 uppercase text-[9px]">Offert</span>}
                    </span>
                    <span className="font-semibold text-slate-800">
                      {isFreeShipping ? 'Gratuit' : shippingCost.toLocaleString('fr-FR', { style: 'currency', currency: 'EUR' })}
                    </span>
                  </div>

                  {!isFreeShipping && (
                    <div className="text-[11px] text-indigo-600 bg-indigo-50/50 p-2 rounded-lg text-center mt-1">
                      Ajoutez encore <span className="font-bold">{(freeShippingThreshold - subtotal).toFixed(2)}€</span> pour débloquer la <span className="font-semibold">livraison offerte</span> !
                    </div>
                  )}

                  <div className="border-t border-slate-200 my-2 pt-2 flex justify-between font-bold text-base text-slate-900 font-sans">
                    <span>Total TTC</span>
                    <span className="text-indigo-600">
                      {total.toLocaleString('fr-FR', { style: 'currency', currency: 'EUR' })}
                    </span>
                  </div>
                </div>

                {/* Bouton de Validation */}
                <button
                  id="checkout-trigger-btn"
                  onClick={() => {
                    onClose();
                    onCheckout();
                  }}
                  className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-sans font-bold text-sm tracking-wide py-3.5 px-6 rounded-xl flex items-center justify-center gap-2 shadow-xs hover:shadow-lg hover:shadow-indigo-100 active:scale-98 transition-all duration-200"
                >
                  Passer au paiement
                  <ArrowRight className="w-4 h-4" />
                </button>

                <div className="flex items-center justify-center gap-1 text-[10px] text-slate-400 font-medium">
                  <ShieldCheck className="w-3.5 h-3.5 text-emerald-500" />
                  <span>Simulation de paiement 100% sécurisée</span>
                </div>

              </div>
            )}

          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
