// vue-version/components/Wishlist.vue
<script setup lang="ts">
import { Heart, Trash2, ShoppingCart, Star } from 'lucide-vue-next';
import { Product } from '../types';

defineProps<{
  favoriteProducts: Product[];
}>();

const emit = defineEmits<{
  (e: 'remove-favorite', productId: string): void;
  (e: 'add-to-cart', product: Product): void;
  (e: 'select-product', product: Product): void;
  (e: 'navigate-to-catalog'): void;
}>();
</script>

<template>
  <div class="space-y-6">
    <!-- En-tête de la vue favoris -->
    <div class="flex items-center justify-between">
      <div>
        <h1 class="font-sans font-extrabold text-2xl text-slate-800 flex items-center gap-2">
          <Heart class="w-6 h-6 text-pink-500 fill-pink-500" />
          <span>Mes favoris</span>
        </h1>
        <p class="text-xs text-slate-500 mt-1">Consultez et ajoutez au panier vos produits enregistrés</p>
      </div>
      <button
        @click="emit('navigate-to-catalog')"
        class="text-xs font-sans font-semibold text-indigo-600 hover:underline cursor-pointer"
      >
        Retourner au catalogue
      </button>
    </div>

    <!-- ÉTAT VIDE : Aucun favoris enregistré -->
    <div 
      v-if="favoriteProducts.length === 0"
      class="bg-white rounded-2xl border border-slate-100 p-12 text-center max-w-lg mx-auto space-y-5"
    >
      <div class="w-16 h-16 rounded-full bg-pink-50 text-pink-500 flex items-center justify-center mx-auto">
        <Heart class="w-8 h-8" />
      </div>
      <div class="space-y-2">
        <h3 class="font-sans font-bold text-slate-800 text-lg">Votre liste est vide</h3>
        <p class="text-xs text-slate-500 leading-relaxed">
          Explorez notre superbe collection et ajoutez des coups de cœur pour les retrouver ici en un clin d'œil.
        </p>
      </div>
      <button
        @click="emit('navigate-to-catalog')"
        class="px-6 py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-sans font-bold text-xs rounded-xl shadow-md shadow-indigo-150 transition-all cursor-pointer"
      >
        Découvrir le catalogue
      </button>
    </div>

    <!-- GRILLE DE PRODUITS FAVORIS -->
    <div v-else class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
      <div
        v-for="product in favoriteProducts"
        :key="product.id"
        class="bg-white rounded-xl border border-slate-100 p-4 flex flex-col hover:border-slate-200 hover:shadow-md transition-all relative group cursor-pointer"
        @click="emit('select-product', product)"
      >
        <!-- Bouton de retrait rapide de la wishlist -->
        <button
          @click.stop="emit('remove-favorite', product.id)"
          class="absolute top-2.5 right-2.5 p-1.5 bg-white/95 rounded-lg border border-slate-100 text-slate-400 hover:text-rose-500 transition-colors shadow-2xs z-10"
          title="Retirer des favoris"
        >
          <Trash2 class="w-4 h-4" />
        </button>

        <!-- Image miniature -->
        <div class="relative aspect-square bg-slate-50 rounded-lg overflow-hidden mb-3">
          <img
            :src="product.mainImage"
            :alt="product.name"
            referrerpolicy="no-referrer"
            class="w-full h-full object-cover group-hover:scale-103 transition-transform duration-300"
          />
        </div>

        <!-- Infos textuelles -->
        <div class="flex-1 flex flex-col justify-between">
          <div>
            <div class="flex items-center gap-1 mb-1">
              <Star class="w-3.5 h-3.5 text-amber-500 fill-amber-500" />
              <span class="text-xs font-mono font-semibold text-slate-600">{{ product.rating }}</span>
            </div>
            <h3 class="font-sans font-bold text-slate-800 text-sm line-clamp-1 group-hover:text-indigo-600 transition-colors">
              {{ product.name }}
            </h3>
            <span class="text-xs text-slate-400 font-sans block mt-0.5 uppercase">{{ product.category }}</span>
          </div>

          <!-- Actions de bas de carte -->
          <div class="flex items-center justify-between border-t border-slate-50 pt-3 mt-4">
            <span class="font-mono font-bold text-sm text-slate-800">
              {{ product.price.toFixed(2) }} €
            </span>

            <button
              :disabled="product.stock === 0"
              @click.stop="emit('add-to-cart', product)"
              class="px-3 py-1.5 bg-indigo-50 hover:bg-indigo-600 text-indigo-600 hover:text-white rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
            >
              <ShoppingCart class="w-3.5 h-3.5" />
              <span>Acheter</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  </div>
</template>

// src/components/Wishlist.tsx
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { Product } from '../types';
import { Heart, Trash2, ShoppingCart, Star } from 'lucide-react';
import { motion } from 'motion/react';

// Props pour la page de wishlist individuelle.
// Analogie VueJS : Props définies pour le composant favoris.
interface WishlistProps {
  favoriteProducts: Product[];
  onRemoveFavorite: (productId: string) => void;
  onAddToCart: (product: Product) => void;
  onSelectProduct: (product: Product) => void;
  onNavigateToCatalog: () => void;
}

export function Wishlist({
  favoriteProducts,
  onRemoveFavorite,
  onAddToCart,
  onSelectProduct,
  onNavigateToCatalog,
}: WishlistProps) {
  return (
    <div id="wishlist-view" className="space-y-6">
      
      {/* En-tête de page */}
      <div>
        <h1 className="font-sans font-extrabold text-2xl lg:text-3xl text-slate-900 tracking-tight flex items-center gap-2">
          <Heart className="w-7 h-7 text-pink-500 fill-pink-500" />
          Mes Coups de Cœur
        </h1>
        <p className="text-sm text-slate-500 mt-1">
          Retrouvez ici tous les articles que vous avez sauvegardés pour plus tard.
        </p>
      </div>

      {favoriteProducts.length === 0 ? (
        /* Écran vide si aucun favori */
        <div className="bg-white rounded-2xl border border-slate-100 p-12 text-center max-w-lg mx-auto space-y-5 shadow-xs">
          <div className="w-16 h-16 rounded-full bg-pink-50 text-pink-500 flex items-center justify-center mx-auto">
            <Heart className="w-8 h-8" />
          </div>
          <div>
            <h3 className="font-sans font-bold text-slate-800 text-lg">Votre liste de favoris est vide</h3>
            <p className="text-xs text-slate-500 mt-1.5 leading-relaxed max-w-sm mx-auto">
              Laissez-vous inspirer par nos meilleures offres ! Naviguez à travers le catalogue et touchez le cœur sur une carte produit pour l'ajouter ici.
            </p>
          </div>
          <button
            id="wishlist-empty-cta"
            onClick={onNavigateToCatalog}
            className="px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-sm font-bold shadow-xs hover:shadow-md transition-all active:scale-95"
          >
            Explorer la boutique
          </button>
        </div>
      ) : (
        /* Grille des Favoris */
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {favoriteProducts.map((product) => {
            const isOutOfStock = product.stock <= 0;
            return (
              <motion.div
                key={`wish-card-${product.id}`}
                layout
                id={`wish-item-${product.id}`}
                className="bg-white rounded-2xl border border-slate-100 shadow-xs hover:shadow-md overflow-hidden flex flex-col group transition-all duration-200"
              >
                {/* Image miniature avec lien de clic */}
                <div 
                  className="aspect-square bg-slate-50 relative cursor-pointer overflow-hidden"
                  onClick={() => onSelectProduct(product)}
                >
                  <img
                    src={product.mainImage}
                    alt={product.name}
                    referrerPolicy="no-referrer"
                    className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-102"
                  />
                  
                  {isOutOfStock && (
                    <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center">
                      <span className="bg-rose-500 text-white font-sans font-bold text-[10px] px-2.5 py-1 rounded-sm uppercase tracking-wider">
                        Rupture
                      </span>
                    </div>
                  )}

                  <span className="absolute top-2.5 left-2.5 bg-white text-[10px] font-bold text-slate-500 px-2 py-0.5 rounded-md border border-slate-100 shadow-none">
                    {product.category}
                  </span>
                </div>

                {/* Détails du produit */}
                <div className="p-4 flex-1 flex flex-col justify-between">
                  <div className="cursor-pointer" onClick={() => onSelectProduct(product)}>
                    <div className="flex items-center text-amber-500 gap-0.5 mb-1">
                      <Star className="w-3 h-3 fill-amber-500" />
                      <span className="text-[11px] font-semibold text-slate-700">{product.rating}</span>
                    </div>

                    <h3 className="font-sans font-bold text-sm text-slate-800 line-clamp-1 group-hover:text-indigo-600 transition-colors">
                      {product.name}
                    </h3>
                    
                    <p className="text-xs text-slate-500 line-clamp-1 mt-0.5">
                      {product.shortDescription}
                    </p>
                  </div>

                  {/* Actions & Prix */}
                  <div className="flex items-center justify-between mt-4 border-t border-slate-50 pt-3">
                    <div>
                      <span className="text-xs font-bold text-slate-800">
                        {product.price.toLocaleString('fr-FR', { style: 'currency', currency: 'EUR' })}
                      </span>
                    </div>

                    <div className="flex items-center gap-1.5">
                      {/* Corbeille pour retirer */}
                      <button
                        id={`wish-remove-btn-${product.id}`}
                        onClick={() => onRemoveFavorite(product.id)}
                        className="p-1.5 rounded-lg text-slate-400 hover:text-rose-500 hover:bg-rose-50 border border-transparent hover:border-rose-100 transition-colors"
                        title="Retirer des favoris"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>

                      {/* Panier pour ajouter directement */}
                      <button
                        id={`wish-add-to-cart-${product.id}`}
                        disabled={isOutOfStock}
                        onClick={() => onAddToCart(product)}
                        className={`p-1.5 rounded-lg border transition-all ${
                          isOutOfStock
                            ? 'bg-slate-50 border-slate-100 text-slate-300 cursor-not-allowed'
                            : 'bg-indigo-50 border-indigo-100 text-indigo-600 hover:bg-indigo-600 hover:text-white hover:border-indigo-600'
                        }`}
                        title={isOutOfStock ? "Indisponible" : "Ajouter au panier"}
                      >
                        <ShoppingCart className="w-4 h-4" />
                      </button>
                    </div>
                  </div>

                </div>
              </motion.div>
            );
          })}
        </div>
      )}
    </div>
  );
}
